name: Upload Sourcemaps to Raygun
description: Upload generated sourcemaps to Raygun
author: Tom Varley
branding:
  icon: activity
  color: gray-dark
inputs:
  token:
    description: Raygun external access token to allow sending of sourcemaps
    required: true
  base_url:
    required: true
    description: The base url of the sourcemap you would like to associate the file with
  folder:
    description: Target folder to check for sourcemaps
    default: './'
runs:
  using: node16
  main: dist/index.js
