name: Action Test
on:
  pull_request:
  push:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Await a workflow
        uses: ./
        with:
          token: asdasd
          base_url: sleep.yml
          folder: short

